### PR TITLE
Set theme jekyll-theme-minimal

### PR DESCRIPTION
**Pull request by lucy-chapar**

### CODE REVIEW

**Comment by lucy-chapar** [comment]
My bad!

**Comment by i-make-robots** [comment]
heh  what were you doing? I'm very curious.

**Comment by lucy-chapar** [comment]
haha I didn't mean to do a merge to your main branch. I'm still learning how to use GitHub! I'm working on a robotic etch-a-sketch and my intent was to modify your super cool puzzle bot code to fit this new purpose. check it out - http://lucianchapar.com/sketchybot/ The intent with this project is to show kids how approachable technology can be with something as ubiquitous as an etch-a-sketch. 

I still don't know a lot about coding, but I've set up LinuxCNC and have experience modifying Marlin firmware for 3D printers... so I'm hoping I'll be able to jump right in here, but we shall see :)

**Comment by lucy-chapar** [comment]
to be specific, I was trying to setup the gh-pages branch on my fork so that I could have sketchybot.github.io online but it didn't work XD

**Pull request closed without merging**
